### ISSUE TITLE
privacytools.io -> privacyguides.org

### ISSUE THREAD

**Issue by 1nc1n3r470r** [reconsidera/reconsidera.github.io#4]
privacytools.io moved to privacyguides.org
https://reddit.com/r/privacytoolsIO/comments/pnql46/rprivacyguides_privacyguidesorg_what_you_need_to/

**Comment by Luterngun** [comment]
[Jonah Aragon's (PrivacyGuides) Failed Attempt to Takeover PrivacyTools.io](https://www.privacytools.io/guides/jonah-aragon-privacyguides-failed-attempt-to-takeover)  
> This long overdue blog post covers the failed takeover attempt of this website, cryptocurrency donations theft, a successful smear campaign, corruption and censorship. All initiated, fabricated by Jonah Aragon, the project lead of PrivacyGuides.org and Aragon Ventures LLC.

**Comment by 1nc1n3r470r** [comment]
> [Jonah Aragon's (PrivacyGuides) Failed Attempt to Takeover PrivacyTools.io](https://www.privacytools.io/guides/jonah-aragon-privacyguides-failed-attempt-to-takeover)
> 
> > This long overdue blog post covers the failed takeover attempt of this website, cryptocurrency donations theft, a successful smear campaign, corruption and censorship. All initiated, fabricated by Jonah Aragon, the project lead of PrivacyGuides.org and Aragon Ventures LLC.

the privacytools.io page is no longer in the possesion of the original team and privacytools.io abuses redirects for affiliate links, so i think the new admin behind privacytools.io is a scammer.

**Comment by 1nc1n3r470r** [comment]
but i have no idea what exactly happened :thinking:
There are a couple things i think are strange though:
- most links on privacytools.io redirect to an affiliate link
- the subreddit is now called "PrivacySoftware" with only one person posting things
- the twitter account retweets following video https://piped.kavin.rocks/watch?v=3cEfJ1UTNvw

this is definitely no definite proof but i found it odd nonetheless.
